src/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import never_cache
from django.views.static import serve

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('product/', include('product.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, view=never_cache(serve))

src/product/urls.py
from django.urls import path
from django.views.generic import TemplateView
from product.views.product import ProductListView, CreateProductView , EditProductView
from product.views.variant import VariantView, VariantCreateView, VariantEditView

app_name = "product"

urlpatterns = [
    # Variants URLs
    path('variants/', VariantView.as_view(), name='variants'),
    path('variant/create/', VariantCreateView.as_view(), name='create.variant'),
    path('variant/<int:pk>/edit/', VariantEditView.as_view(), name='update.variant'),

    # Products URLs
    path('create/', CreateProductView.as_view(), name='create.product'),
    path('list/', ProductListView.as_view(), name='list.product'),
    path('<int:pk>/edit/', EditProductView.as_view(), name='edit_product_detail'),

    
]

src/product/models.py
from django.db import models
from config.g_model import TimeStampMixin
import json


class Variant(TimeStampMixin):
    title = models.CharField(max_length=40, unique=True)
    description = models.TextField()
    active = models.BooleanField(default=True)


class Product(TimeStampMixin):
    title = models.CharField(max_length=255)
    sku = models.SlugField(max_length=255, unique=True)
    description = models.TextField()
    active = models.BooleanField(default=True)

    
    
    # Reverse relationship to get variants associated with the product
    variants = models.ManyToManyField('ProductVariant', related_name='products')

    # Variant info field
    variant_info = models.TextField(blank=True)

    def save(self, *args, **kwargs):
        variant_info = []
        for variant in self.variants.all():
            variant_info.append({
                'id': variant.id,
                'title': variant.variant_title,
                'variant': variant.variant.title
            })
        print(variant_info) # Add this line to check if variant_info is properly collected
        self.variant_info = json.dumps(variant_info)
        super().save(*args, **kwargs)



class ProductImage(TimeStampMixin):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    file_path = models.URLField()


class ProductVariant(TimeStampMixin):
    variant_title = models.CharField(max_length=255)
    variant = models.ForeignKey(Variant, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_variants')


class ProductVariantPrice(TimeStampMixin):
    product_variant_one = models.ForeignKey(ProductVariant, on_delete=models.SET_NULL, null=True, related_name='product_variant_one')
    product_variant_two = models.ForeignKey(ProductVariant, on_delete=models.SET_NULL, null=True, related_name='product_variant_two')
    product_variant_three = models.ForeignKey(ProductVariant, on_delete=models.SET_NULL, null=True, related_name='product_variant_three')
    price = models.FloatField()
    stock = models.FloatField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

src/product/forms.py
from django.forms import forms, ModelForm, CharField, TextInput, Textarea, BooleanField, CheckboxInput

from product.models import Variant, Product
from django import forms


class VariantForm(ModelForm):
    class Meta:
        model = Variant
        fields = '__all__'
        widgets = {
            'title': TextInput(attrs={'class': 'form-control'}),
            'description': Textarea(attrs={'class': 'form-control'}),
            'active': CheckboxInput(attrs={'class': 'form-check-input', 'id': 'active'})
        }

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'description', 'active',]
        widgets = {
            'title': TextInput(attrs={'class': 'form-control'}),
            'description': Textarea(attrs={'class': 'form-control'}),
            'active': CheckboxInput(attrs={'class': 'form-check-input', 'id': 'active'}),
            
        }

src/product/views/product.py
from django.views import generic
from django.views.generic import ListView
from django.db import models
from django.core.paginator import Paginator
from django.views.generic import ListView
from django.shortcuts import render
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.utils import timezone
from django.shortcuts import render, get_object_or_404

from rest_framework.views import APIView
from rest_framework.response import Response
from product.models import Variant
from django.shortcuts import render
from django.views import View
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy

from product.models import ProductVariantPrice, Variant, Product

class CreateProductView(generic.TemplateView):
    template_name = 'products/create.html'

    def product_detail(request, slug):
        product = get_object_or_404(Product, slug=slug)
        variants = Variant.objects.filter(product=product, active=True).values('id', 'title').annotate(price=models.Min('prices__price'), stock=models.Sum('prices__stock'))
        return render(request, 'products/product_detail.html', {'product': product, 'variants': variants})

class EditProductView(UpdateView):
    model = Product
    template_name = 'edit_product.html'
    fields = ['title', 'sku', 'description', 'active', 'variants', 'variant_info'] # Add 'variants' to fields

    def get_success_url(self):
        return reverse_lazy('product:list.product')


class Variants(APIView):
    def get_price(self, variant):
        variant_price = ProductVariantPrice.objects.filter(variant=variant).first()
        if variant_price:
            return variant_price.price
        return None

    def get_stock(self, variant):
        variant_price = ProductVariantPrice.objects.filter(variant=variant).first()
        if variant_price:
            return variant_price.stock
        return None

    def get(self, request):
        variants = Variant.objects.filter(active=True)
        variant_list = []
        for variant in variants:
            price = self.get_price(variant)
            stock = self.get_stock(variant)
            variant_dict = {
                'id': variant.id,
                'title': variant.title,
                'price': price,
                'stock': stock,
            }
            variant_list.append(variant_dict)
        return Response(variant_list)



class ProductListView(ListView):
    template_name = 'products/list.html'
    queryset = Product.objects.all()
    paginate_by = 5  # Change this to adjust the number of items per page

    def get_queryset(self):
        queryset = super().get_queryset()

        # Apply filters based on GET parameters
        title = self.request.GET.get('title')
        variant = self.request.GET.get('variant')
        price_from = self.request.GET.get('price_from')
        price_to = self.request.GET.get('price_to')
        date = self.request.GET.get('date')

        if title:
            queryset = queryset.filter(title__icontains=title)
        if variant:
            queryset = queryset.filter(variant=variant)
        if price_from and price_to:
            queryset = queryset.filter(price__range=(price_from, price_to))
        if date:
            queryset = queryset.filter(created_at__date=date)

        # Pass the variant value to the context
        variant_value = variant if variant else '--Select A Variant--'
        self.extra_context = {'variant': variant_value}

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = Paginator(self.queryset, self.paginate_by)
        page = self.request.GET.get('page')
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            products = paginator.page(1)
        except EmptyPage:
            # If page is out of range, deliver last page of results.
            products = paginator.page(paginator.num_pages)

        # Define the range of pages to show in the pagination
        index = products.number - 1
        max_index = len(paginator.page_range)
        start_index = index - 5 if index >= 5 else 0
        end_index = index + 5 if index <= max_index - 5 else max_index
        page_range = list(paginator.page_range[start_index:end_index])

        context['products'] = products
        context['product_list'] = products  # Add the paginator object to the context
        context['products_start'] = (products.number - 1) * self.paginate_by + 1  # Define products_start
        context['products_end'] = min(products.number * self.paginate_by, paginator.count)  # Define products_end
        context['page_num'] = int(page) if page else 1  # Add page_num to the context
        context['page_range'] = page_range  # Add page_range to the context

        return context

src/product/views/variant.py
from django.views import generic
from django.views.generic import ListView, CreateView, UpdateView

from product.forms import VariantForm
from product.models import Variant


class BaseVariantView(generic.View):
    form_class = VariantForm
    model = Variant
    template_name = 'variants/create.html'
    success_url = '/product/variants'


class VariantView(BaseVariantView, ListView):
    template_name = 'variants/list.html'
    paginate_by = 10

    def get_queryset(self):
        filter_string = {}
        print(self.request.GET)
        for key in self.request.GET:
            if self.request.GET.get(key):
                filter_string[key] = self.request.GET.get(key)
        return Variant.objects.filter(**filter_string)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = True
        context['request'] = ''
        if self.request.GET:
            context['request'] = self.request.GET['title__icontains']
        return context


class VariantCreateView(BaseVariantView, CreateView):
    pass


class VariantEditView(BaseVariantView, UpdateView):
    pk_url_kwarg = 'id'

src/product/templates/products/create.html
{% extends 'backend/base.html' %}

{% block title %} Create Product {% endblock %}

{% block content %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Create Product</h1>
    <a href="{% url 'product:create.product' %}" class="float-right btn btn-primary">All Product</a>
</div>

<div id="app">
    <create-product :variants="{{variants|safe}}"></create-product>
</div>

{% endblock %}

src/product/templates/products/edit_product.html
{% extends 'backend/base.html' %}

{% block title %} Edit Product {% endblock %}

{% block content %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Edit Product</h1>
    <a href="{% url 'product:list.product' %}" class="float-right btn btn-primary">All Products</a>
</div>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save Changes</button>
</form>

{% endblock %}

src/product/templates/products/list.html
{% extends 'backend/base.html' %}
{% load static %}
{% block title %} Product List {% endblock %}
<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
{% block content %}
<div id="app">
    {% if product_list %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Products</h1>
    </div>

    <div class="card">
        <form action="{% url 'product:list.product' %}" method="get" class="card-header">
            <div class="form-row justify-content-between">
                <div class="col-md-2">
                    <input type="text" name="title" placeholder="Product Title" class="form-control"
                        value="{{ request.GET.title }}">
                </div>
                <div class="col-md-2">
                    <select name="variant" id="" class="form-control">
                        <option selected disabled value="--Select A Variant--">--Select A Variant--</option>
                    </select>
                </div>






                <div class="col-md-3">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Price Range</span>
                        </div>
                        <input type="text" name="price_from" aria-label="First name" placeholder="From"
                            class="form-control" value="{{ request.GET.price_from }}">
                        <input type="text" name="price_to" aria-label="Last name" placeholder="To" class="form-control"
                            value="{{ request.GET.price_to }}">
                    </div>
                </div>
                <div class="col-md-2">
                    <input type="date" name="date" placeholder="Date" class="form-control"
                        value="{{ request.GET.date }}">
                </div>
                <div class="col-md-1">
                    <button type="submit" class="btn btn-primary float-right"><i class="fa fa-search"></i></button>
                </div>
            </div>
        </form>
    </div>
    <div class="card-body">
        <div class="table-response">
            <table class="table">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Variant</th>
                        <th width="150px">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for product in product_list %}
                    <tr>
                        <td>{{ product.pk }}</td>
                        <td>{{ product.title }}<br> Created at : {{ product.created_at }}</td>
                        <td>{{ product.description }}</td>
                        <td>
                            {% for variant in product.variants.all %}
                            <dl class="row mb-0" style="height: 80px; overflow: hidden">
                                <dt class="col-sm-3 pb-0">{{ variant.title }}</dt>
                                <dd class="col-sm-9">
                                    <dl class="row mb-0">
                                        <dd class="col-sm-4 pb-0">Price : {{ variant.price }}</dd>
                                        <dd class="col-sm-8 pb-0">InStock : {{ variant.stock }}</dd>
                                    </dl>
                                </dd>
                            </dl>
                            {% endfor %}
                        </td>


                        <td>
                            <a href="{% url 'product:edit_product_detail' product.id %}" class="btn btn-primary">Edit</a>
                        </td>

                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="5">No products found.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer">
        <div class="row justify-content-between">
            <div class="card-footer">
                <div class="row justify-content-between">
                    <div class="col-md-6">
                        <p>Showing {{ product_list.start_index }} to {{ product_list.end_index }} out of {{product_list|length }} products</p>
                    </div>
                    <div class="col-md-6">
                        <nav>
                            <ul class="pagination">
                                {% if products.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ products.previous_page_number }}">&laquo;</a>
                                </li>
                                {% endif %}
                                {% for page in page_range %}
                                <li class="page-item{% if products.number == page %} active{% endif %}">
                                    <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                                </li>
                                {% endfor %}
                                {% if products.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ products.next_page_number }}">&raquo;</a>
                                </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
</div>
{% else %}
<p>No products found.</p>
{% endif %}
{% endblock %}
</div>